### ISSUE TITLE
Doesn't work in windows cmd prompt

### ISSUE THREAD

**Issue by k1nger** [dataminr/generator-reactjs-flux#2]
Documentation says "On Windows, we suggest you use an improved command line tool such as cmder or PowerShell to **improve** the experience."

That implies to me that it would at least work in the windows cmd prompt, I would change documentation to state the the usage of tools such as cmder or PowerShell are a necessity or change the code to make it run in windows cmd prompt as well.

The specific step that doesn't work is the shell:cleanCompiledDirectory grunt tasks because of the rm -rf app/compiled.

The equivalent in windows is rd /s /q app/compiled

**Comment by jasonjohnson115** [comment]
We currently do not run this on any Windows machines. I apologize the implementation of the grunt tasks has grown to be specific to a Unix environment. Feel free to submit a pull request with Windows support. We would greatly appreciate the contribution. Potentially, using something like Cygwin should get you further along with getting this up and running. Thanks for the feedback!
